name: PHP Syntax Checker

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, cs2pr

    - name: Validate syntax
      run: |
        find . -name "*.php" -exec php -l {} \; | cs2pr
